### ISSUE TITLE
Start date: Start date must be lower than end date.

### ISSUE THREAD

**Issue by avoinea** [eaudeweb/mac-logging#33]
Working time Input:
* Start: 09/10/2017
* End:  09/10/2017

Ar trebuie sa fie `<=` ca sa poți filtra și ziua curentă.

**Comment by melish** [comment]
poti filtra ziua curenta pentru că End date nu e inclus în selecție

**Comment by avoinea** [comment]
TypeError: can't compare datetime.date to NoneType
