### ISSUE TITLE
Hours not properly tracked 

### ISSUE THREAD

**Issue by alecghica** [eaudeweb/mac-logging#39]
My (Alexandru Ghica) tracked hours based on MAC address of my mobile are not properly tracked. E.g. today (24.10.2017) I was in the office from 10:20 AM to 11:30 PM and last hours tracked were from days ago.

**Comment by catalinjitea** [comment]
We haven't implemented a method to track the "end date" yet, so the end date should be start date + 8h. Right now I see that you were tracked 3 days consecutive, so if the problem persist don't hesitate to contact me. Also, please make sure that you connect your device to the network at the very first moment when you arrive to work.
