### ISSUE TITLE
Styling for /clocking

### ISSUE THREAD

**Issue by alexmuscalu23** [eaudeweb/mac-logging#7]
- Rename the save button to choose or pick
- Change color of the button to info or dark http://getbootstrap.com/docs/4.0/utilities/colors/
- Change the styling for select https://silviomoreto.github.io/bootstrap-select/examples/

**Comment by andreeadima** [comment]
One other way to approach that select would be to change it into a datepicker https://bootstrap-datepicker.readthedocs.io/en/latest/
